global:
  smtp_smarthost: '127.0.0.1:25'
  smtp_from: 'alertmanager@company.com'

route:
  receiver: 'catchall-mail'

  routes:
   
   - match:
       team: "admins"
     receiver: 'joe@company.com-mail'
   


receivers:
- name: 'catchall-mail'
  email_configs:
  - to: 'catchall@company.com'
    require_tls: false

- name: 'joe@company.com-mail'
  email_configs:
  - to: 'joe@company.com'
    require_tls: false

