global:
  scrape_interval:     15s 
  evaluation_interval: 15s
  external_labels:
    monitor: 'prom-monitor'

rule_files:
  - /opt/config/prometheus.rules

scrape_configs:
  - job_name: 'prometheus'

    scrape_interval: 5s
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'node'
    static_configs:
      - targets:
         - nodeexp:9100
